<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Mutable-Default-Argument-and-Function" data-toc-modified-id="Mutable-Default-Argument-and-Function-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Mutable Default Argument and Function</a></span><ul class="toc-item"><li><span><a href="#Example-of-mutable-object-is-used-in-function-argument" data-toc-modified-id="Example-of-mutable-object-is-used-in-function-argument-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Example of mutable object is used in function argument</a></span></li><li><span><a href="#Solution-to-use-mutable-objects-in-function-argument" data-toc-modified-id="Solution-to-use-mutable-objects-in-function-argument-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Solution to use mutable objects in function argument</a></span></li></ul></li><li><span><a href="#Function-Arguments" data-toc-modified-id="Function-Arguments-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Function Arguments</a></span><ul class="toc-item"><li><span><a href="#The-unpacking-operator-(*)" data-toc-modified-id="The-unpacking-operator-(*)-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>The unpacking operator (*)</a></span></li><li><span><a href="#**kwargs" data-toc-modified-id="**kwargs-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>**kwargs</a></span></li><li><span><a href="#Put-everything-together" data-toc-modified-id="Put-everything-together-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Put everything together</a></span></li><li><span><a href="#Unpacking-and-packing" data-toc-modified-id="Unpacking-and-packing-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Unpacking and packing</a></span><ul class="toc-item"><li><span><a href="#In-the-below,-asterisk-*-unpacks-the-my_num_list-into-3-number-to-put-into-the-sum-function" data-toc-modified-id="In-the-below,-asterisk-*-unpacks-the-my_num_list-into-3-number-to-put-into-the-sum-function-2.4.1"><span class="toc-item-num">2.4.1&nbsp;&nbsp;</span>In the below, asterisk * unpacks the my_num_list into 3 number to put into the sum function</a></span></li><li><span><a href="#Similar-unpacking-is-applied-with-double-asterisks-**" data-toc-modified-id="Similar-unpacking-is-applied-with-double-asterisks-**-2.4.2"><span class="toc-item-num">2.4.2&nbsp;&nbsp;</span>Similar unpacking is applied with double asterisks **</a></span></li><li><span><a href="#Unpacking-can-also-be-used-inside-function" data-toc-modified-id="Unpacking-can-also-be-used-inside-function-2.4.3"><span class="toc-item-num">2.4.3&nbsp;&nbsp;</span>Unpacking can also be used inside function</a></span></li><li><span><a href="#Unpacking-parts-of-an-iterable" data-toc-modified-id="Unpacking-parts-of-an-iterable-2.4.4"><span class="toc-item-num">2.4.4&nbsp;&nbsp;</span>Unpacking parts of an iterable</a></span></li><li><span><a href="#Merging-iterables" data-toc-modified-id="Merging-iterables-2.4.5"><span class="toc-item-num">2.4.5&nbsp;&nbsp;</span>Merging iterables</a></span></li><li><span><a href="#Combine-packing-and-unpacking" data-toc-modified-id="Combine-packing-and-unpacking-2.4.6"><span class="toc-item-num">2.4.6&nbsp;&nbsp;</span>Combine packing and unpacking</a></span></li></ul></li></ul></li><li><span><a href="#Functions-Deep-Dive" data-toc-modified-id="Functions-Deep-Dive-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Functions Deep Dive</a></span><ul class="toc-item"><li><span><a href="#Lambda-Functions" data-toc-modified-id="Lambda-Functions-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Lambda Functions</a></span></li><li><span><a href="#Functions-as-First-Class-Objects" data-toc-modified-id="Functions-as-First-Class-Objects-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Functions as First-Class Objects</a></span><ul class="toc-item"><li><span><a href="#First-class-objects-can-be-stored-as-variables." data-toc-modified-id="First-class-objects-can-be-stored-as-variables.-3.2.1"><span class="toc-item-num">3.2.1&nbsp;&nbsp;</span>First-class objects can be stored as variables.</a></span></li><li><span><a href="#Functions-as-Arguments" data-toc-modified-id="Functions-as-Arguments-3.2.2"><span class="toc-item-num">3.2.2&nbsp;&nbsp;</span>Functions as Arguments</a></span></li><li><span><a href="#Functions-as-Return-Values" data-toc-modified-id="Functions-as-Return-Values-3.2.3"><span class="toc-item-num">3.2.3&nbsp;&nbsp;</span>Functions as Return Values</a></span></li></ul></li><li><span><a href="#Built-In-Higher-Order-Functions:-map(),-filter(),-reduce()" data-toc-modified-id="Built-In-Higher-Order-Functions:-map(),-filter(),-reduce()-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Built-In Higher-Order Functions: map(), filter(), reduce()</a></span></li></ul></li></ul></div>

## Mutable Default Argument and Function

Examples of mutable objects:
- list
- set
- dictionary

Examples of immutable objects:
- int, float or other numbers
- Tupples are kind of immutable list
- Strings are immutable as strings are returned a completely new strings when they are updated.

When using mutable object in function argument, one (1) and only one (1) object is created.

### Example of mutable object is used in function argument

In [8]:
def update_order(new_item, current_order=[]):
    current_order.append(new_item)
    return current_order


# First order, burger
order1 = update_order({'item': 'burger', 'cost': '3.50'})

print(f"order1 is: {order1}")

# Second order, just a soda
order2 = update_order({'item': 'soda', 'cost': '1.50'})

# What's in that second order again?
print(f"order2 is: {order2}")
print(f"order1 is: {order1}")

order1 is: [{'item': 'burger', 'cost': '3.50'}]
order2 is: [{'item': 'burger', 'cost': '3.50'}, {'item': 'soda', 'cost': '1.50'}]
order1 is: [{'item': 'burger', 'cost': '3.50'}, {'item': 'soda', 'cost': '1.50'}]


In the above, current_order is used as a list in argument of function update_order. The function append the new_item into the argument current_order, and finally return the current_order
- In order1, first item of {{'item': 'burger', 'cost': '3.50'} is used for the argument new_item
- In order2, we would expect that it would be {'item': 'soda', 'cost': '1.50'}. However, it is returning the list appended into order1. And we get order1 and order2 have the same value finally.

Reason: order1 and order2 are just pointers to the same location in memory, which is assigned to current_order list. This can be proved as below when both orders have the same id.

In [11]:
print(id(order1))
print(id(order2))

2472442436864
2472442436864


### Solution to use mutable objects in function argument

The solution is to combine None and if as below

In [12]:
def update_order(new_item, current_order=None):
    if current_order == None:
        current_order = []
    current_order.append(new_item)
    return current_order


# First order, burger
order1 = update_order({'item': 'burger', 'cost': '3.50'})


print(f"order1 is: {order1}")


# Second order, just a soda
order2 = update_order({'item': 'soda', 'cost': '1.50'})

# What's in that second order again?
print(f"order2 is: {order2}")
print(f"order1 is: {order1}")

order1 is: [{'item': 'burger', 'cost': '3.50'}]
order2 is: [{'item': 'soda', 'cost': '1.50'}]
order1 is: [{'item': 'burger', 'cost': '3.50'}]


## Function Arguments

### The unpacking operator (\*)

It is storing its following argument passed into the function in the form of a tuple.

In [24]:
def my_function(*args):
    print(args)
    print(type(args))

my_function("hello", 2, False)

('hello', 2, False)
<class 'tuple'>


In [19]:
# This is to print them into a string
def my_function(*args):
    s=""
    for arg in args:
        s = f"{s} {arg}"
        
    s.strip()
    
    print(s)
    

my_function("hello", 2, False)

 hello 2 False


**Another example**

In [22]:
tables = {
  1: {
    'name': 'Jiho',
    'vip_status': False,
    'order': 'Orange Juice, Apple Juice'
  },
  2: {},
  3: {},
  4: {},
  5: {},
  6: {},
  7: {},
}
print(tables)

def assign_table(table_number, name, vip_status=False): 
  tables[table_number]['name'] = name
  tables[table_number]['vip_status'] = vip_status
  tables[table_number]['order'] = ''

# Assign order into table_number
def assign_and_print_order(table_number, *order_items):
  tables[table_number]["order"] = order_items
  for item in order_items:
    print(item)

# Add a new customer named 'Arwa' to table 2 with a VIP status set to True
assign_table(2, "Arwa", True)

# Now that Arwa is seated and ready to order, call our assign_and_print_order() function for table 2 with the order items of 'Steak', 'Seabass', and 'Wine Bottle'
assign_and_print_order(2, "Steak", "Seabass", "Wine Bottle")

print(tables)

{1: {'name': 'Jiho', 'vip_status': False, 'order': 'Orange Juice, Apple Juice'}, 2: {}, 3: {}, 4: {}, 5: {}, 6: {}, 7: {}}
Steak
Seabass
Wine Bottle
{1: {'name': 'Jiho', 'vip_status': False, 'order': 'Orange Juice, Apple Juice'}, 2: {'name': 'Arwa', 'vip_status': True, 'order': ('Steak', 'Seabass', 'Wine Bottle')}, 3: {}, 4: {}, 5: {}, 6: {}, 7: {}}


### **kwargs

Double asterisks ** allow for unlimited keyword arguments

In [23]:
def arbitrary_keyword_args(**kwargs):
  print(type(kwargs))
  print(kwargs)
  # See if there's an 'anything_goes' keyword arg and print it
  print(kwargs.get('anything_goes'))
 
arbitrary_keyword_args(this_arg='wowzers', anything_goes=101)

<class 'dict'>
{'this_arg': 'wowzers', 'anything_goes': 101}
101


**Another example**

In [27]:
tables = {
  1: {
    'name': 'Chioma',
    'vip_status': False,
    'order': {
      'drinks': 'Orange Juice, Apple Juice',
      'food': 'Pancakes'
    }
  },
  2: {},
  3: {},
  4: {},
  5: {},
  6: {},
  7: {},
}
print(tables)


# Write your code below: 
def assign_food_items(**order_items):
  print(order_items)
  food = order_items.get("food")
  drinks = order_items.get("drinks")
  print(food)
  print(drinks)

# Example Call
assign_food_items(food='Pancakes, Poached Egg', drinks='Water')

{1: {'name': 'Chioma', 'vip_status': False, 'order': {'drinks': 'Orange Juice, Apple Juice', 'food': 'Pancakes'}}, 2: {}, 3: {}, 4: {}, 5: {}, 6: {}, 7: {}}
{'food': 'Pancakes, Poached Egg', 'drinks': 'Water'}
Pancakes, Poached Egg
Water


**Last example**

In [34]:
def print_data(positional_arg, **data):
    print(positional_arg)
    for arg in data.values():
        print(arg)
 
print_data('position 1', a='arg1', b=True, c=100)

position 1
arg1
True
100


### Put everything together

In [35]:
def print_animals(animal1, animal2, *args, animal4, **kwargs):
    print(animal1, animal2)
    print(args)
    print(animal4)
    print(kwargs)
    
print_animals('Snake', 'Fish', 'Guinea Pig', 'Owl', animal4='Cat', animal5='Dog', animal6='Tiger')

Snake Fish
('Guinea Pig', 'Owl')
Cat
{'animal5': 'Dog', 'animal6': 'Tiger'}


### Unpacking and packing

#### In the below, asterisk * unpacks the my_num_list into 3 number to put into the sum function

In [41]:
my_num_list = [3, 6, 9]
 
def sum(num1, num2, num3):
  print(num1 + num2 + num3)
 
sum(*my_num_list)
print(*my_num_list)

18
3 6 9


#### Similar unpacking is applied with double asterisks **

In [44]:
numbers  = {'num1': 3, 'num2': 6, 'num3': 9}
 
def sum(num1, num2, num3):
  print(num1 + num2 + num3)
 
sum(**numbers)

18


#### Unpacking can also be used inside function

In [45]:
start_and_stop = [3, 6]
 
range_values = range(*start_and_stop)
print(list(range_values))

[3, 4, 5]


#### Unpacking parts of an iterable

In [46]:
 a, *b, c = [3, 6, 9, 12, 15]
 print(b)

[6, 9, 12]


#### Merging iterables

In [47]:
my_tuple = (3, 6, 9)
merged_tuple = (0, *my_tuple, 12)
print(merged_tuple)

(0, 3, 6, 9, 12)


#### Combine packing and unpacking

In [49]:
num_collection = [3, 6, 9]
 
def power_two(*nums): # Packing with *args
  for num in nums:
    print(num**2)
 
power_two(*num_collection) # Unpacking

9
36
81


## Functions Deep Dive

### Lambda Functions
It is a way to write a function in 1 line.

In [1]:
def early_or_late(arriving_time):
    if arriving_time<8:
        print("early")
    else:
        print("late")

early_or_late(9)

late


In [3]:
# Rewrite the above by using lambda
early_or_late = lambda arriving_time: print("early") if arriving_time<8 else print("late")

early_or_late(9)

late


### Functions as First-Class Objects

All functions are First-Class Objects, which means:
- First-class objects can be stored as variables.
- First-class objects can be passed as arguments to a function.
- First-class objects can be returned by a function.
- First-class objects can be stored in data structures (e.g., lists, dictionaries, etc.).

#### First-class objects can be stored as variables.

In [5]:
# Here, we assign a function to a variable
uppercase = str.upper 
 
# And then call it 
big_pie = uppercase("pumpkinpie")

# or store function into a list
string_manipulation_functions = [str.upper, str.lower] 

#### Functions as Arguments

Example:

```Python
def total_bill(func, value):
    total = func(value)
    return total
```

In [9]:
def total_bill(func, value):
  total = func(value)
  return total

def add_tax(total):
  tax = total * 0.06
  new_total = total + tax
  return new_total

# total_bill call function add_tax and a variable
print(total_bill(add_tax, 100))

def add_tip(total):
  tip = total * .2
  new_total = total + tip
  return new_total
 
#total_bill call function add_tip and a variable
print(total_bill(add_tip, 100))

106.0
120.0


total_bill is the higher-order function as it takes in an argument which is a function.

The real power is to keep manipulation despite whatever function is put into as the input argument

In [10]:
def total_bill(func, value):
  total = func(value)
  return ("The total amount owed is $" + "{:.2f}".format(total) + ". Thank you! :)")
 
 
print(total_bill(add_tax, 100))
print(total_bill(add_tip, 100))

The total amount owed is $106.00. Thank you! :)
The total amount owed is $120.00. Thank you! :)


We can use the higher-order function with a list:

```Python

def total_bills(func, list):
    # This list will store all the new bill values
    new_bills = []
 
    # This loop will iterate through our bills
    for i in range(len(list)):
 
        # Here we apply the function to each element of the list!
        total = func(list[i])
        new_bills.append("Total amount owed is $" + "{:.2f}".format(total) + ". Thank you! :)")
 
  return new_bills
  
```

#### Functions as Return Values

In [17]:
def make_box_volume_function(height):
    # defines and returns a function that takes two numeric arguments,        
    # length &  width, and returns the volume given the input height
    def volume(length, width):
        return length*width*height
 
    return volume
 
# box_volume_heights is a volume function requiring 2 variable length and width;
# interestingly, it is generated with the attached height of 15.
box_volume_height15 = make_box_volume_function(15)
 
print(box_volume_height15(3,2))

90


In [13]:
box_volume_height10 = make_box_volume_function(10)
 
print(box_volume_height10(3,2))

60


### Built-In Higher-Order Functions: map(), filter(), reduce()

These are are higher-order function to iterate throught the list. Details can be found in the below link.

https://github.com/son-n-pham/Python_Good-Tips/blob/main/README.md